CREATE TABLE [dbo].[ASN]
(
	[ASNID] INT IDENTITY NOT NULL CONSTRAINT [PK_ASN_ASNID] PRIMARY KEY,
	[Context] XML NOT NULL,
	[Revision] SMALLINT NOT NULL,
	[Status] VARCHAR(20) NOT NULL,
	[FileName] VARCHAR(100) NOT NULL,
	[BuyerOrderReference] VARCHAR(50) NOT NULL,
	[SellerOrderReference] VARCHAR(50) NOT NULL,
	[ASNSent] BIT NOT NULL,
	[ASNSentDate] SMALLDATETIME NULL,
	[IsActive] BIT NOT NULL,
	[SupplierName] VARCHAR(100) NOT NULL
)