CREATE TABLE [dbo].[History]
(
	[HistoryID] INT IDENTITY NOT NULL CONSTRAINT [PK_History_HistoryID] PRIMARY KEY,
	[PurchaseOrderID] INT NULL CONSTRAINT [FK_History_PurchaseOrderID] FOREIGN KEY REFERENCES [PurchaseOrder]([PurchaseOrderID]),
	[ASNID] INT NULL CONSTRAINT [FK_History_ASNID] FOREIGN KEY REFERENCES [ASN]([ASNID]),
	[PODID] INT NULL CONSTRAINT [FK_History_PODID] FOREIGN KEY REFERENCES [POD]([PODID]),
	[EventType] VARCHAR(30) NOT NULL,
	[EventDescription] VARCHAR(50) NULL,
	[EventDate] SMALLDATETIME NOT NULL
)
