CREATE TABLE [dbo].[POD]
(
	[PODID] INT IDENTITY NOT NULL CONSTRAINT [PK_POD_PODID] PRIMARY KEY,
	[Context] XML NOT NULL,
	[Revision] SMALLINT NOT NULL,
	[Status] VARCHAR(20) NOT NULL,
	[FileName] VARCHAR(100) NOT NULL,
	[OrderReference] VARCHAR(50) NOT NULL,
	[PODSent] BIT NOT NULL,
	[PODSentDate] SMALLDATETIME NULL,
	[IsActive] BIT NOT NULL,
	[SupplierName] VARCHAR(100) NOT NULL
)
